"""
=========================================================
LLM Module (Local Chat Model)
Project : AI Mental Health Chatbot (FYP)

Reusable local LLM factory for the chatbot backend.

This module is responsible ONLY for creating and returning a
configured ChatOllama instance.
=========================================================
"""

from langchain_ollama import ChatOllama


# -------------------------------------------------------
# Defaults
# -------------------------------------------------------

DEFAULT_MODEL_NAME = "llama3.2:1b"
DEFAULT_TEMPERATURE = 0.3
DEFAULT_NUM_PREDICT = 150


# =======================================================
# LLM Factory
# =======================================================

def get_llm(
    model_name: str = DEFAULT_MODEL_NAME,
    temperature: float = DEFAULT_TEMPERATURE,
    num_predict: int = DEFAULT_NUM_PREDICT,
    **kwargs,
) -> ChatOllama:
    """
    Create and return a configured local ChatOllama instance.

    Args:
        model_name:
            Name of the Ollama model installed locally.

        temperature:
            Controls randomness of the generated response.

        num_predict:
            Maximum number of tokens generated by the model.

        **kwargs:
            Additional ChatOllama parameters.

    Returns:
        ChatOllama instance ready for inference.
    """

    return ChatOllama(
        model=model_name,
        temperature=temperature,
        num_predict=num_predict,
        **kwargs,
    )


# =======================================================
# Command Line Mode
# =======================================================

if __name__ == "__main__":

    print("==============================")
    print("LLM Module")
    print("==============================")

    llm = get_llm()

    print(f"Selected model   : {DEFAULT_MODEL_NAME}")
    print(f"Temperature      : {DEFAULT_TEMPERATURE}")
    print(f"Max output       : {DEFAULT_NUM_PREDICT}")
    print("LLM instance created successfully.")